### ISSUE TITLE
validating keyring stuf in CI

### ISSUE THREAD

**Issue by Arend-Jan** [Arend-Jan/dsh#42]
In the CI we don't have enough right for using the keyring service of the os. this might be a solution:
If you want to skip certain tests when running in a CI environment, you could use an environment variable to control this behavior. 

In your Rust tests, you can add a conditional statement that checks if a certain environment variable is set. If it is, you can return early from the test:

```rust
#[test]
fn test_something() {
    if std::env::var("CI").is_ok() {
        println!("Running in CI, skipping test");
        return;
    }

    // Your test code here...
}
```

In this example, the test will be skipped if the `CI` environment variable is set. 

Then, in your CI configuration file, you can set the `CI` environment variable to any value. Here is an example for GitHub Actions:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
        env:
          CI: true
```

In this example, the `CI` environment variable is set to `true` for the "Run tests" step. So, when the tests are run, the `CI` environment variable will be set and any tests using the above pattern will be skipped.

Remember that this will also skip any other tests that check for the `CI` environment variable. If you want to skip only certain tests, you could use a different environment variable for each test you want to skip.
